### ISSUE TITLE
Trying to run ThermalNetwork to size borefields but running into an error

### ISSUE THREAD

**Issue by tanushree04** [NREL/ThermalNetwork#39]
### Describe the bug
Seeing following error : 

`KeyError: 'soil'`
### To Reproduce

thermalnetwork -y .\demos\sdk_output_skeleton_13_buildings\run\baseline_scenario\ghe_dir\sys_params_proportional.json -s .\demos\sdk_output_skeleton_13_buildings\run\baseline_scenario\ -f .\demos\sdk_output_skeleton_13_buildings\exportGeo.json -o .\demos\sdk_output_skeleton_13_buildings\run\baseline_scenario\ghe_dir\

### Expected behavior
It should create a GFunction in GHEDesigner and update the system parameter file with borehole numbers and length

### Desktop (please complete the following information):
Windows OS

### Additional context
Full error : 

Traceback (most recent call last):
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code     
    exec(code, run_globals)
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\Scripts\thermalnetwork.exe\__main__.py", line 7, in <module>
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
n\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\site-packages\thermalnetwork\network.py", line 678, in run_sizer_from_cli
    return run_sizer_from_cli_worker(
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\site-packages\thermalnetwork\network.py", line 595, in run_sizer_from_cli_worker
    network_data: list[dict] = network.convert_features(connected_features)
  File "C:\Users\tcharan\AppData\Local\Programs\Python\Python310\lib\site-packages\thermalnetwork\network.py", line 201, in convert_features
    "soil": self.ghe_parameters["soil"],
KeyError: 'soil'

**Comment by vtnate** [comment]
This is due to a difference between the released version and the current `main` branch. In https://github.com/NREL/ThermalNetwork/pull/37 we moved the `soil` parameter up one level, as it is used for horizontal piping and not exclusively for `ghe_parameters`. Until we make a release this means our versions of sys-param files will be out-of-sync and need to be adapted manually to go from one to the other.

**Comment by mitchute** [comment]
@vtnate @tanushree04 can this be closed?

**Comment by vtnate** [comment]
Fixed in v0.3.0
