### ISSUE TITLE
Thermal Network IndexError

### ISSUE THREAD

**Issue by tanushree04** [NREL/ThermalNetwork#46]
### Describe the bug
Getting an error when running TN 0.3.0 using the UO CLI

...ThermalNetwork found with specified version 0.3.0
...urbanopt-ditto-reader found with specified version 0.6.4
...NREL-disco found with specified version 0.5.1
...geojson-modelica-translator found with specified version 0.8.0
[14:05:12] DEBUG    system_parameter_file=WindowsPath('ghe_project_3/sys_param.json')                                                                                           network.py:851
           DEBUG    scenario_directory=WindowsPath('C:/Users/tcharan/urbanopt-cli/ghe_project_3/run/baseline_scenario')                                                         network.py:852
           DEBUG    geojson_file=WindowsPath('ghe_project_3/balanced_load.json')                                                                                                network.py:853
           DEBUG    output_directory=WindowsPath('C:/Users/tcharan/urbanopt-cli/ghe_project_3/run/baseline_scenario/ghe_dir')                                                   network.py:854
           WARNING  Mismatched ThermalNetwork versions. Could be a problem. The system_parameter.json version is 1.0, but the ThermalNetwork version is 0.3.0.                  network.py:736
           DEBUG    ghe_design_data={'method': 'AREAPROPORTIONAL', 'flow_rate': 0.2, 'flow_type': 'borehole', 'max_eft': 35.0, 'min_eft': 5.0}                                  network.py:743
Traceback (most recent call last):
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\Scripts\thermalnetwork.exe\__main__.py", line 7, in <module>
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\thermalnetwork\network.py", line 860, in run_sizer_from_cli
    return run_sizer_from_cli_worker(system_parameter_file, scenario_directory, geojson_file, output_directory)
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\thermalnetwork\network.py", line 748, in run_sizer_from_cli_worker
    connected_features = network.get_connected_features()
  File "C:\Users\tcharan\urbanopt-cli\example_files\python_deps\python-3.10\lib\site-packages\thermalnetwork\network.py", line 82, in get_connected_features
    if feature["properties"]["id"] == [connected_features[0]] and feature["properties"]["type"] != "Building":
IndexError: list index out of range

### To Reproduce
I am attaching my geojson file and sys param file.

Command used: 
`bundle exec uo ghe_size -y .\ghe_project_3\sys_param.json -s .\ghe_project_3\baseline_scenario.csv -f .\ghe_project_3\balanced_load.json`

### Expected behavior
TN sizes GHE

### Desktop (please complete the following information):
 - Windows
[balanced_load.json](https://github.com/user-attachments/files/17722828/balanced_load.json)
[sys_param.json](https://github.com/user-attachments/files/17722829/sys_param.json)

**Comment by tanushree04** [comment]
I manually added the  "is_ghe_start_loop": true property to the junction connected to the GHE, and got past this error.

This property is not added automatically using the UO internal UI

**Comment by mitchute** [comment]
Thanks. Does this need to be documented on the UO repo?

**Comment by tanushree04** [comment]
Yes, added a feature request https://github.com/urbanopt/urbanopt-cli/issues/491
